### PR TITLE
Content

### PR DESCRIPTION
**Pull request by AntBezr**
## Link to feature environment:
http://localhost:3000/

## Changes proposed in this PR:

Some minor changes in the config 
New database with content 

## How to test:

**BEFORE STARTING CREATE BACKUP** `lando db-export`  **(Just in case)**

`git fetch origin content`
`git checkout content`
`lando drush cim`
`lando db-import DBnewContent.sql.gz`

check the localhost.... 
I'm not sure if pictures also will be in this DB 
If u switch to finish language there should be almost all the same content except events. Events don't support translation at all

### CODE REVIEW

**Comment by julilan** [comment]
Seems like in the [config update](https://github.com/BCH-Wunder-Project-team-4/Wunder.io/pull/52/commits/7b5b802b43def0328c044b87f15afe28e77d8168) commit a lot of the the renaming of labels are reverted (also RIP help text 😆). Just checking if there was an issue with them. It's not a big thing if the label namings are reverted. Mostly they were for readability's sake :D
Screenshot 2023-12-18 at 21 58 33

I'm more worried about this since it helps to not send empty speaker paragraphs to front.
Screenshot 2023-12-18 at 22 07 38

**Comment by AntBezr** [comment]
To be honest I cannot remember what was the reason for renaming Speakers and event Location. But it seems to me that it was a bit misleading for me or something like this. 
Event speaker name required  was changed to false because sometimes it might be big event and under do not host it, but trying to promote, like this one https://wunder.io/articles/wunder-experts-sharing-productivity-boosting-discoveries-at-drupalcon-lille-2023/

**Comment by AntBezr** [comment]
Sorry, I probably should asked you before I made these changes

**Comment by julilan** [comment]
> https://wunder.io/articles/wunder-experts-sharing-productivity-boosting-discoveries-at-drupalcon-lille-2023/

No worries, I originally changed some the label names just so they would be more easy to read (no underscores etc). More of a cosmetic change since it doesn't affect the machine names.

**Comment by julilan** [comment]
Amazing work with the content. 

Some Finglish here and there but we be multilingual 😎

**Review by julilan — APPROVED** [review]
We have content and images 👏

All the pages are filled/working except About / Contact that will be added in next PRs.

Content types rendering without issues.

Will be easier to test the site now that we have content showing.

**Review by markusVJH — APPROVED** [review]
Looks good! Working

**Pull request merged**
