### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by markusVJH**
## Link to ticket:

[Dark mode design](https://trello.com/c/d48Lgy1t/79-dark-mode-design)
[Dark mode](https://trello.com/c/qeTUmbQG/80-dark-mode)

## Changes proposed in this PR:

- Installed next-themes and implemented darkmode functionality. 
- Dark mode button in the header
- Base colors for both light and dark in globals.css and some components

## How to test:

1. git checkout darkMode
2. npm install
3. magic

Screenshot 2023-11-24 at 11 33 35

### CODE REVIEW

**Comment by markusVJH** [comment]
[Dark mode](https://trello.com/c/qeTUmbQG/80-dark-mode)

**Comment by markusVJH** [comment]
[Dark mode design](https://trello.com/c/d48Lgy1t/79-dark-mode-design)

**Review by julilan — CHANGES_REQUESTED** [review]
Looking and working like magic 🪄 

One small thing I spotted is that we could adjust the size of the ThemeButton icon so it is similar size to other icons in the header

Here's one solution:
Screenshot 2023-11-24 at 13 46 55
Screenshot 2023-11-24 at 13 46 38

**Comment by markusVJH** [comment]
Size fixed! Much cleaner now
Screenshot 2023-11-24 at 14 13 41

**Review by julilan — APPROVED** [review]
✨

**Pull request merged**
